spring:
  application:
    name: parking


  datasource:
    url: ${DB_URL}
    username: ${DB_UNAME}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true

  messages:
    basename: messages

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_UNAME}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP} # in milliseconds