spring:
    application:
         name: parking


    datasource:
      url: ${DB_URL}
      username: ${DB_UNAME}
      password: ${DB_PASS}

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
      show-sql: true

    messages:
      basename: messages


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP} # in milliseconds